[book]
authors = ["maochunguang"]
language = "en"
multilingual = false
src = "src"
title = "java offer终结者"
description = "java找工作，offer终结者！" 

[build]
build-dir = "_book"                # the directory where the output is placed
create-missing = true  


[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "light"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding

[output.html.search]
enable = true            # enables the search feature
limit-results = 30       # maximum number of search results
teaser-word-count = 30   # number of words used for a search result teaser
use-boolean-and = true   # multiple search terms must all match
boost-title = 2          # ranking boost factor for matches in headers
boost-hierarchy = 1      # ranking boost factor for matches in page names
boost-paragraph = 1      # ranking boost factor for matches in text
expand = true            # partial words will match longer terms
heading-split-level = 3  # link results to heading levels
copy-js = true           # include Javascript code for search